import { Metadata } from "next";

export const metadata: Metadata = {
	title: "Nare App",
	description: "Generated by create next app",
};

export default function ContactPage() {
	return (
		<>
			<span className='text-7xl'>Contact</span>
		</>
	);
}
